import { z } from "zod";

// MCP tools (yolo-v1.md §10). Annotations follow the table exactly: read
// tools are readOnly, deletions are destructive, everything else is marked
// non-destructive explicitly because MCP defaults destructiveHint to true.

const READ_ONLY = Object.freeze({ readOnlyHint: true, destructiveHint: false, openWorldHint: false });
const WRITE = Object.freeze({ readOnlyHint: false, destructiveHint: false, openWorldHint: false });
const DESTRUCTIVE = Object.freeze({ readOnlyHint: false, destructiveHint: true, openWorldHint: false });

const url = z.string().describe("Video or page URL, e.g. a YouTube or Bilibili link");
const itemId = z.string().describe("Library item id from search or browse, e.g. \"plex:12345\"");
const queuePosition = z.enum(["next", "end"]).describe("\"next\" plays it after the current item; \"end\" appends");
const playlistId = z.string().describe("Playlist id from playlist_list");
const device = z.string().describe("Device name or id from list_devices. Omit to use the active device");

export const TOOLS = [
  {
    name: "get_status",
    title: "Get playback status",
    description: "What is playing now, on which device, the position, whether the home media node is online, and what is up next.",
    scope: "read",
    annotations: READ_ONLY,
    input: z.object({}),
    run: (services) => services.status(),
  },
  {
    name: "list_devices",
    title: "List devices",
    description: "Screens that can play, such as the Drive-In player in the car, with online and active flags.",
    scope: "read",
    annotations: READ_ONLY,
    input: z.object({}),
    run: (services) => services.devices(),
  },
  {
    name: "search",
    title: "Search the library",
    description: "Search the media library (movies, shows, episodes) by title. If the query is a URL, resolve its title, duration and thumbnail instead. Use the returned ids with play, queue_add, or playlist_add.",
    scope: "read",
    annotations: READ_ONLY,
    input: z.object({
      query: z.string().min(1).describe("Title to search for, or a URL to look up"),
      type: z.enum(["movie", "show", "episode"]).optional().describe("Only return this kind of item"),
    }),
    run: (services, args) => services.search(args),
  },
  {
    name: "browse",
    title: "Browse the library",
    description: "Without arguments, list libraries. With library_id, list that library's items (newest first). With item_id, list a show's episodes or another item's children.",
    scope: "read",
    annotations: READ_ONLY,
    input: z.object({
      library_id: z.string().optional().describe("Library id from browse"),
      item_id: itemId.optional(),
      offset: z.number().int().min(0).optional(),
      limit: z.number().int().min(1).max(200).optional(),
    }),
    run: (services, args) => services.browse({ libraryId: args.library_id, itemId: args.item_id, offset: args.offset, limit: args.limit }),
  },
  {
    name: "play",
    title: "Play",
    description: "Start playing a URL, a library item, or a queue item, replacing what is playing. Plays on the active device unless device is given. Resumes from the last saved position unless start_at is given.",
    scope: "control",
    annotations: WRITE,
    input: z.object({
      url: url.optional(),
      item_id: itemId.optional(),
      queue_item_id: z.string().optional().describe("Queue item id from queue_list; it is removed from the queue"),
      device: device.optional(),
      start_at: z.number().min(0).optional().describe("Start position in seconds"),
    }),
    run: (services, args) => services.play({
      url: args.url, itemId: args.item_id, queueItemId: args.queue_item_id, device: args.device, startAt: args.start_at,
    }),
  },
  {
    name: "control",
    title: "Control playback",
    description: "Pause, resume, or stop playback, or skip to the next queue item or the previous history item.",
    scope: "control",
    annotations: WRITE,
    input: z.object({ action: z.enum(["pause", "resume", "stop", "next", "previous"]) }),
    run: (services, args) => services.control(args.action),
  },
  {
    name: "seek",
    title: "Seek",
    description: "Jump to a position in the current item.",
    scope: "control",
    annotations: WRITE,
    input: z.object({ position_seconds: z.number().min(0) }),
    run: (services, args) => services.seek(args.position_seconds),
  },
  {
    name: "transfer",
    title: "Transfer playback",
    description: "Move playback to another device and continue from the same position. The previous device stops.",
    scope: "control",
    annotations: WRITE,
    input: z.object({ device: z.string().describe("Device name or id from list_devices") }),
    run: (services, args) => services.transfer(args.device),
  },
  {
    name: "list_tracks",
    title: "List subtitle and audio tracks",
    description: "Subtitle and audio tracks for the current item, or for item_id (a library item id or URL).",
    scope: "read",
    annotations: READ_ONLY,
    input: z.object({ item_id: z.string().optional().describe("Library item id or URL; omit for the current item") }),
    run: (services, args) => services.listTracks(args.item_id ? { itemId: args.item_id } : {}),
  },
  {
    name: "set_tracks",
    title: "Choose subtitles and audio",
    description: "Choose subtitle and audio tracks for the current item using ids from list_tracks. Pass subtitles: [] to turn subtitles off. The choice is remembered for similar videos.",
    scope: "control",
    annotations: WRITE,
    input: z.object({
      subtitles: z.array(z.string()).max(4).optional().describe("Subtitle track ids; [] turns subtitles off"),
      audio: z.string().optional().describe("Audio track id"),
    }),
    run: (services, args) => services.setTracks(args),
  },
  {
    name: "queue_list",
    title: "List the queue",
    description: "Items waiting to play after the current one, in order.",
    scope: "read",
    annotations: READ_ONLY,
    input: z.object({}),
    run: (services) => services.listQueue(),
  },
  {
    name: "queue_add",
    title: "Add to the queue",
    description: "Add a URL or library item to the queue, at the end or to play next.",
    scope: "manage",
    annotations: WRITE,
    input: z.object({ url: url.optional(), item_id: itemId.optional(), position: queuePosition.optional() }),
    run: (services, args) => services.addToQueue({ url: args.url, itemId: args.item_id, position: args.position }),
  },
  {
    name: "queue_remove",
    title: "Remove from the queue",
    description: "Remove one item from the queue.",
    scope: "manage",
    annotations: DESTRUCTIVE,
    input: z.object({ queue_item_id: z.string().describe("Queue item id from queue_list") }),
    run: (services, args) => services.removeFromQueue(args.queue_item_id),
  },
  {
    name: "queue_clear",
    title: "Clear the queue",
    description: "Remove every item from the queue. Does not stop what is playing.",
    scope: "manage",
    annotations: DESTRUCTIVE,
    input: z.object({}),
    run: (services) => services.clearQueue(),
  },
  {
    name: "playlist_list",
    title: "List playlists",
    description: "Saved playlists with item counts.",
    scope: "read",
    annotations: READ_ONLY,
    input: z.object({}),
    run: (services) => services.listPlaylists(),
  },
  {
    name: "playlist_get",
    title: "Show a playlist",
    description: "A saved playlist and its items.",
    scope: "read",
    annotations: READ_ONLY,
    input: z.object({ playlist_id: playlistId }),
    run: (services, args) => services.getPlaylist(args.playlist_id),
  },
  {
    name: "playlist_create",
    title: "Create a playlist",
    description: "Create an empty saved playlist.",
    scope: "manage",
    annotations: WRITE,
    input: z.object({ name: z.string().min(1).max(200), description: z.string().max(2000).optional() }),
    run: (services, args) => services.createPlaylist(args),
  },
  {
    name: "playlist_add",
    title: "Add to a playlist",
    description: "Add a URL or library item to the end of a saved playlist.",
    scope: "manage",
    annotations: WRITE,
    input: z.object({ playlist_id: playlistId, url: url.optional(), item_id: itemId.optional() }),
    run: (services, args) => services.addToPlaylist(args.playlist_id, { url: args.url, itemId: args.item_id }),
  },
  {
    name: "playlist_import",
    title: "Import a playlist",
    description: "Save an external playlist (for example a YouTube or Bilibili playlist URL) as a new playlist, optionally adding it to the queue.",
    scope: "manage",
    annotations: WRITE,
    input: z.object({
      url: z.string().describe("External playlist URL"),
      name: z.string().max(200).optional().describe("Name for the saved playlist; defaults to the source title"),
      enqueue: z.boolean().optional().describe("Also add every item to the end of the queue"),
    }),
    run: (services, args) => services.importPlaylist(args),
  },
  {
    name: "playlist_enqueue",
    title: "Queue a playlist",
    description: "Add every item of a saved playlist to the queue.",
    scope: "manage",
    annotations: WRITE,
    input: z.object({ playlist_id: playlistId, position: queuePosition.optional() }),
    run: (services, args) => services.enqueuePlaylist(args.playlist_id, { position: args.position }),
  },
  {
    name: "playlist_delete",
    title: "Delete a playlist",
    description: "Delete a saved playlist and its items.",
    scope: "manage",
    annotations: DESTRUCTIVE,
    input: z.object({ playlist_id: playlistId }),
    run: (services, args) => services.deletePlaylist(args.playlist_id),
  },
  {
    name: "history",
    title: "Watch history",
    description: "Recently played items, newest first, with the saved position for resuming.",
    scope: "read",
    annotations: READ_ONLY,
    input: z.object({ limit: z.number().int().min(1).max(500).optional() }),
    run: (services, args) => services.history({ limit: args.limit }),
  },
];
